### ISSUE TITLE
缺少inject文件，

### ISSUE THREAD

**Issue by thouger** [IIIImmmyyy/ImyLinker#1]
请问在app/src/main/cpp/native-lib.cpp下的
`
void loadSo() {
    my_dlopen("/data/local/tmp/inject", RTLD_NOW);
}
`
inject这个文件，是一个什么文件呢？缺少了这个，无法启动app

**Comment by IIIImmmyyy** [comment]
这个是测试自定义linker加载的so  随便编译一个so 输出hellow就行

**Comment by thouger** [comment]
> 这个是测试自定义linker加载的so 随便编译一个so 输出hellow就行

明白，成功了，非常感谢
